version: '3'

services:
  php:
    image: php:8.1.18-fpm
    volumes:
      - './source:/var/www/html'
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './source:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
  mariadb:
    image: mariadb:10.9
    ports:
      - 3306:3306
    volumes:
      - ./docker/mariadb/database:/var/lib/mysql
      - ./docker/mariadb/dump:/home
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=blog_db
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=monty
      - MARIADB_PASSWORD=monty
