version: '3'

services:
  o_php:
    build: ./docker/php
    volumes:
      - './source:/var/www/html'
      - "./docker/conf/db.ini:/var/www/html/db.ini:rw"
    depends_on:
      - o_mariadb

  o_nginx:
    image: nginx:latest
    ports:
      - 8084:80
    volumes:
      - './source:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

  o_mariadb:
      image: mariadb:10.9
      ports:
        - 3311:3306
      volumes:
        - ./docker/mariadb/database:/var/lib/mysql
        - ./docker/mariadb/dump:/var/backups:rw
      env_file:
      - ./docker/conf/db.ini
