version: '3'

services:
  o_php:
    build: ./php
    volumes:
      - './source:/var/www/html'
    depends_on:
      - o_mariadb  
    networks:
      - space

  o_nginx:
    image: nginx:latest
    ports:
      - 8083:80
    volumes:
      - './source:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    networks:
      - space

  o_mariadb:
    image: mariadb:10.9
    ports:
      - 3310:3306
    volumes:
      - ./docker/mariadb/database:/var/lib/mysql
      - ./docker/mariadb/dump:/home
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=blog_db
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=monty
      - MARIADB_PASSWORD=monty
    networks:
      - space